package apresentacao;

import modelo.Controle;

public class frmPrincipal extends javax.swing.JDialog
{
    public frmPrincipal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnFacil = new javax.swing.JRadioButton();
        btnMedio = new javax.swing.JRadioButton();
        btnDificil = new javax.swing.JRadioButton();
        lblNome = new javax.swing.JLabel();
        txfNome = new javax.swing.JTextField();
        lblDificuldade = new javax.swing.JLabel();
        btnComeçar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnFacil.setText("Facil");
        btnFacil.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFacilActionPerformed(evt);
            }
        });

        btnMedio.setText("Medio");
        btnMedio.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMedioActionPerformed(evt);
            }
        });

        btnDificil.setText("Dificil");
        btnDificil.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDificilActionPerformed(evt);
            }
        });

        lblNome.setText("Digite seu Nome");

        lblDificuldade.setText("Escolha a dificuldade desejada");

        btnComeçar.setText("Começar");
        btnComeçar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnComeçarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnComeçar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txfNome)
                    .addComponent(lblDificuldade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblNome)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(129, 129, 129))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDificil, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMedio)
                    .addComponent(btnFacil))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNome)
                .addGap(18, 18, 18)
                .addComponent(txfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDificuldade)
                .addGap(29, 29, 29)
                .addComponent(btnFacil)
                .addGap(18, 18, 18)
                .addComponent(btnMedio)
                .addGap(18, 18, 18)
                .addComponent(btnDificil)
                .addGap(28, 28, 28)
                .addComponent(btnComeçar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnComeçarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnComeçarActionPerformed
    {//GEN-HEADEREND:event_btnComeçarActionPerformed
    Controle controle = new Controle();
    
     if(btnFacil.isSelected())
     {
         controle.dificuldade(btnFacil.getText());
     }
     
     if(btnMedio.isSelected())
     {
         controle.dificuldade(btnMedio.getText());
     }
     
     if(btnDificil.isSelected())
     {
         controle.dificuldade(btnDificil.getText());
     }
     
     frmQuiz quiz = new frmQuiz(null, true);
     this.setVisible(false);
     quiz.setVisible(true);
    }//GEN-LAST:event_btnComeçarActionPerformed

    private void btnDificilActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDificilActionPerformed
    {//GEN-HEADEREND:event_btnDificilActionPerformed
    }//GEN-LAST:event_btnDificilActionPerformed

    private void btnMedioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMedioActionPerformed
    {//GEN-HEADEREND:event_btnMedioActionPerformed
    }//GEN-LAST:event_btnMedioActionPerformed

    private void btnFacilActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFacilActionPerformed
    {//GEN-HEADEREND:event_btnFacilActionPerformed
    }//GEN-LAST:event_btnFacilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmPrincipal dialog = new frmPrincipal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComeçar;
    private javax.swing.JRadioButton btnDificil;
    private javax.swing.JRadioButton btnFacil;
    private javax.swing.JRadioButton btnMedio;
    private javax.swing.JLabel lblDificuldade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTextField txfNome;
    // End of variables declaration//GEN-END:variables
}
