package apresentacao;

import java.awt.Color;
import javax.swing.JOptionPane;
import modelo.Controle;
import modelo.Quiz;
import modelo.Pontuacao;

public class frmQuiz extends javax.swing.JDialog
{
    public frmQuiz(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        
        btnPergunta1.setEnabled(false);
        btnPergunta2.setEnabled(false);
        btnPergunta3.setEnabled(false);
        btnPergunta1.setVisible(false);
        btnPergunta2.setVisible(false);
        btnPergunta3.setVisible(false);
    }

    Controle controle = new Controle();
    Quiz quiz = new Quiz();
    Pontuacao pontuacao = new Pontuacao();
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnePrincipal = new javax.swing.JPanel();
        lblPergunta = new javax.swing.JLabel();
        btnPergunta1 = new javax.swing.JRadioButton();
        btnPergunta2 = new javax.swing.JRadioButton();
        btnPergunta3 = new javax.swing.JRadioButton();
        btnConfirmar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));

        pnePrincipal.setBackground(new java.awt.Color(0, 204, 204));

        lblPergunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPergunta.setText("Seja Bem vindo ao ao QUIZ sustentável ");
        lblPergunta.setAlignmentX(1.5F);
        lblPergunta.setAlignmentY(0.0F);
        lblPergunta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153), new java.awt.Color(0, 153, 153)));
        lblPergunta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnPergunta1.setBackground(new java.awt.Color(0, 153, 153));
        btnPergunta1.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        btnPergunta1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPergunta1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPergunta1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPergunta1ActionPerformed(evt);
            }
        });

        btnPergunta2.setBackground(new java.awt.Color(0, 153, 153));
        btnPergunta2.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        btnPergunta2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPergunta2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnPergunta3.setBackground(new java.awt.Color(0, 153, 153));
        btnPergunta3.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        btnPergunta3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPergunta3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        btnConfirmar.setBackground(new java.awt.Color(204, 204, 204));
        btnConfirmar.setText("Começar");
        btnConfirmar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirmar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnePrincipalLayout = new javax.swing.GroupLayout(pnePrincipal);
        pnePrincipal.setLayout(pnePrincipalLayout);
        pnePrincipalLayout.setHorizontalGroup(
            pnePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPergunta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPergunta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPergunta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnePrincipalLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnePrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(332, 332, 332))
        );
        pnePrincipalLayout.setVerticalGroup(
            pnePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnePrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnPergunta1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPergunta2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPergunta3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnePrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnConfirmarActionPerformed
    {//GEN-HEADEREND:event_btnConfirmarActionPerformed
        btnConfirmar.setText("Próxima");
        lblPergunta.setVisible(true);
        btnPergunta1.setEnabled(true);
        btnPergunta2.setEnabled(true);
        btnPergunta3.setEnabled(true);
        btnPergunta1.setVisible(true);
        btnPergunta2.setVisible(true);
        btnPergunta3.setVisible(true);

        if (btnPergunta1.isSelected())
        {
            controle.verificarResposta(btnPergunta1.getText());
            btnPergunta1.setSelected(false);
        }

        if (btnPergunta2.isSelected())
        {
            controle.verificarResposta(btnPergunta2.getText());
            btnPergunta2.setSelected(false);
        }

        if (btnPergunta3.isSelected())
        {
            controle.verificarResposta(btnPergunta3.getText());
            btnPergunta3.setSelected(false);
        }

        controle.IniciarQuiz();
        lblPergunta.setText(controle.pergunta);
        btnPergunta1.setText(controle.opcao[0]);
        btnPergunta2.setText(controle.opcao[1]);
        btnPergunta3.setText(controle.opcao[2]);

        if (controle.getEstado().equals("resultado"))
        {
            JOptionPane.showMessageDialog(null, "Pontos: " + pontuacao.getPonto());
            btnConfirmar.setText("Confirmar");
            lblPergunta.setVisible(false);
            btnPergunta1.setEnabled(false);
            btnPergunta2.setEnabled(false);
            btnPergunta3.setEnabled(false);
            btnPergunta1.setVisible(false);
            btnPergunta2.setVisible(false);
            btnPergunta3.setVisible(false);
            btnConfirmar.setEnabled(false);
            btnConfirmar.setVisible(false);
        }
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnPergunta1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnPergunta1ActionPerformed
    {//GEN-HEADEREND:event_btnPergunta1ActionPerformed
    }//GEN-LAST:event_btnPergunta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmQuiz dialog = new frmQuiz(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JRadioButton btnPergunta1;
    private javax.swing.JRadioButton btnPergunta2;
    private javax.swing.JRadioButton btnPergunta3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPergunta;
    private javax.swing.JPanel pnePrincipal;
    // End of variables declaration//GEN-END:variables
}
